version: 2.1

workspace_root: &workspace_root
  /tmp/workspace

cmd_attach_workspace: &cmd_attach_workspace
  attach_workspace:
    at: *workspace_root

jobs:
  for_4_04_0:
    executor: for_4_04_0
    steps:
      - test
  for_4_05_0:
    executor: for_4_05_0
    steps:
      - test
  for_4_06_0:
    executor: for_4_06_0
    steps:
      - test

commands:
  test:
    steps:
      - checkout
      - *cmd_attach_workspace
      - run: pwd
      - run: ls -la
      - run:
          name: Install the dependencies
          command: eval $(opam config env) && opam install -y . --deps-only
      - run:
          name: Build the Psyche compiler
          command: eval $(opam config env) && make
      - run:
          name: Update PATH
          command: echo "export PATH=/tmp/workspace/compiler/_build:$PATH" >> $BASH_ENV
      - run:
          name: Run tests
          command: eval $(opam config env) && make test

executors:
  for_4_04_0:
    docker:
      - image: 0918nobita/psyche-docker:for-ocaml-4.04.0
    working_directory: *workspace_root
  for_4_05_0:
    docker:
      - image: 0918nobita/psyche-docker:for-ocaml-4.05.0
    working_directory: *workspace_root
  for_4_06_0:
    docker:
      - image: 0918nobita/psyche-docker:for-ocaml-4.06.0
    working_directory: *workspace_root

workflows:
  main:
    jobs:
      - for_4_04_0
      - for_4_05_0
      - for_4_06_0
