version: 2.1

workspace_root: &workspace_root
  /tmp/workspace

cmd_attach_workspace: &cmd_attach_workspace
  attach_workspace:
    at: *workspace_root

jobs:
  unit_test:
    executor: build_executor
    steps:
      - checkout
      - *cmd_attach_workspace
      - cmd_pwd
      - cmd_ls
      - run:
          name: Build the Psyche compiler
          command: eval $(opam config env) && make
          working_directory: compiler
      - run:
          command: sudo mv psyche /usr/bin/psyche
          working_directory: compiler/_build
      - run:
          name: Run tests
          command: make test
          working_directory: test-suite

commands:
  cmd_pwd:
    description: Display `pwd` to increase an observability & debugging
    steps:
      - run: pwd
  cmd_ls:
    description: Display `ls -al` to increase an observability & debugging
    steps:
      - run: ls -la

executors:
  build_executor:
    docker:
      - image: 0918nobita/psyche-docker:latest
    working_directory: *workspace_root

workflows:
  main:
    jobs:
      - unit_test
