name: Lint

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize]

jobs:
  rustfmt:
    name: Check Rust code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run rustfmt
        run: cargo fmt -- --check
