name: Lint

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Exec fantomas
        run: |
          dotnet fantomas --recurse --check --pageWidth 90 ./src
          dotnet fantomas --recurse --check --pageWidth 90 ./tests
