name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['2.2.401', '2.1.801']
    steps:
    - uses: actions/checkout@v1
    - run: pwd && ls -la
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
    - run: dotnet run --project compiler/src/App.Tests
