name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: pwd && ls -la
    - run: dotnet run --project compiler/src/App.Tests
