name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        dotnet-version: ['2.2.401']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Test package
        run: dotnet run --project src/Tests
